package nhlApi

//copy JSON toGO
//delete copyright
type Autogenerated struct {
	Teams []struct {
		ID    int    `json:"id"`
		Name  string `json:"name"`
		Link  string `json:"link"`
		Venue struct {
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Abbreviation    string `json:"abbreviation"`
		Teamname        string `json:"teamName"`
		Locationname    string `json:"locationName"`
		Firstyearofplay string `json:"firstYearOfPlay,omitempty"`
		Division        struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
			Link string `json:"link"`
		} `json:"division,omitempty"`
		Conference struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
			Link string `json:"link"`
		} `json:"conference,omitempty"`
		Franchise struct {
			Franchiseid int    `json:"franchiseId"`
			Teamname    string `json:"teamName"`
			Link        string `json:"link"`
		} `json:"franchise"`
		Shortname       string `json:"shortName,omitempty"`
		Officialsiteurl string `json:"officialSiteUrl"`
		Franchiseid     int    `json:"franchiseId"`
		Active          bool   `json:"active"`
		Venue           struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Venue struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			Link     string `json:"link"`
			City     string `json:"city"`
			Timezone struct {
				ID     string `json:"id"`
				Offset int    `json:"offset"`
				Tz     string `json:"tz"`
			} `json:"timeZone"`
		} `json:"venue,omitempty"`
		Division struct {
			Link string `json:"link"`
		} `json:"division,omitempty"`
		Conference struct {
			Link string `json:"link"`
		} `json:"conference,omitempty"`
	} `json:"teams"`
}
